import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "../../styles/globals.css";
import AuthScreenHeader from "../shared/AuthScreenHeader";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        // ${geistSans.variable} ${geistMono.variable}
        <html lang="en">
            <body
                className={`flex flex-col gap-[60px] h-full mx-auto`}
            >
                <AuthScreenHeader />
                <main className="mx-auto flex items-center justify-center w-full h-auto">
                    {children}
                </main>
            </body>
        </html>
    );
}
